### ISSUE TITLE
Not work with Next.js 12

### ISSUE THREAD

**Issue by webcredo** [typesense/showcase-nextjs-typesense-ecommerce-store#4]
## Description

This example does not work with Next.js 12 with React 18

**Next.js Version**:

12.2.5

## Steps to reproduce
Same example on Next.js 12 with React 18

**Typsense Version**:
2.4.1

**Comment by webcredo** [comment]
It works with new React InstantSearch Hooks https://www.algolia.com/doc/guides/building-search-ui/widgets/showcase/react-hooks/

**Comment by rkanani108** [comment]
Hi @jasonbosco,

It is still open. Is there any update?

Regards,
Rakesh Kanani

**Comment by jasonbosco** [comment]
@rkanani108 This is an issue with instantsearch: https://github.com/typesense/showcase-nextjs-typesense-ecommerce-store/issues/3#issuecomment-1175983069
